// THIS FILE IS AUTOGENERATED
// DO NOT EDIT THIS FILE!

import * as lunr from "lunr";
require("lunr-languages/lunr.stemmer.support")(lunr);
require("lunr-languages/lunr.zh")(lunr);
export default lunr;
